# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 154734

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Clear Node modules cache
              run: npm cache clean --force

            - name: npm install, and build
              run: |
                  npm install --workspaces=false
                  npm run build --if-present
              working-directory: packages/express-backend
            - name: Zip artifact for deployment
              run: zip release.zip ./* -r
              working-directory: packages/express-backend
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: release-artifact
                  path: packages/express-backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: release-artifact

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_359FA02E03C146EC9D47E32A2FD3EE8E }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9308AB1ED1724DACA724BB2BE6BA6372 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_786F5C6B9B0442E491CDEF6D1233C34D }}

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "154734"
                  slot-name: "Production"
                  package: release.zip
